### ISSUE TITLE
Icons don't load in Sapper

### ISSUE THREAD

**Issue by LostCrew** [moollaza/svelte-zondicons#2]
**Describe the bug**
In Sapper, Importing and rendering an icon, as described in README, triggers the following error:

> `<Icon>` is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

**Expected behavior**
The page loads and the icon displays.

**Desktop (please complete the following information):**
 - OS: MacOS X 10.14.6
 - Browser: Firefox
 - Version: 72.0b10

**Additional context**
Thanks to [this thread](https://github.com/RobBrazier/svelte-awesome/issues/506#issuecomment-557647896), the bug seems to not occuring if icon is imported as follows:

```
import SearchIcon from 'svelte-zondicons/src/icons/Search.svelte';
```  

Given the above, I'm not sure whether any fix for named imports for Sapper would be possible.

**Comment by moollaza** [comment]
@LostCrew I'm currently using the library with a Sapper project (default Rollup config, should I believe that's SSR?) and I'm unable to produce this warning.

Can you explain more about your setup? Do you have a code snippet, or an example that can re-create the issues.

>Thanks to this thread, the bug seems to not occuring if icon is imported as follows:

I saw this before I made the lib and was expecting issues, but was happily surprised that I didn't have any so you may be correct that there's simply no good solution here beside importing as described. Perhaps there's a better way to build/export the components though to avoid this?

I'm still learning Svelte/Sapper so I'm definitely not an expert.

**Comment by LostCrew** [comment]
Sure. Let's take this import:

https://github.com/tripletapp/frontend/blob/4e042bd84b2f09ee3ed303e5fc27d3b408089da1/src/components/BrandText.svelte#L9

The error triggers when Menu icon is imported as named import:

```
import MenuIcon from 'svelte-zondicons/src/icons/Menu.svelte';
```

For setup details and dependency versions, I'm developing that project locally. Feel free to check it out and run it on your local machine too.

I'm also learning Svelte/Sapper as we speak. I'm unfortunately not able to give you pointers to fixing this just yet.

**Comment by moollaza** [comment]
@LostCrew Hmm. It appears to work correctly for me:
- I cloned your repo
- installed deps via `yarn`
- started dev server via `yarn dev`
- visited localhost:3000

I saw the icon, and didn't see any warnings in the terminal or browser consoles. FWIW, I'm using Node v12.14.0

![tripletapp-zondicons-working](https://user-images.githubusercontent.com/873785/71539100-350f6c80-2905-11ea-81ca-1f431477a8b7.png)

**Comment by moollaza** [comment]
@LostCrew are you still having issues? If not I'd like to close this out unless I can reproduce the issue

**Comment by LostCrew** [comment]
Sorry, not a lot of time to look at this right now. I'll get back to you soon

**Comment by moollaza** [comment]
Closing this for now, as it seems to work correctly for me.
